services:
  api:
    build: .
    container_name: awebo-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - awebo-network

networks:
  awebo-network:
    external: true
    name: awebo-network

volumes:
  postgres_data:
  uploads_data:

