services:
  api:
    build: .
    container_name: awebo-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
<<<<<<< Updated upstream
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      db:
        condition: service_healthy
=======
    networks:
      - awebo-network

networks:
  awebo-network:
    external: true
    name: awebo-network
>>>>>>> Stashed changes

volumes:
  postgres_data:
  uploads_data:

